무피게시글 리스트
SELECT 
   BD.BD_NO
  , U.NICKNAME
  , BD.BD_NAME
  , BD.BD_CONTENT
  , BD.BD_REGDATE
  , BD.BD_UPDATE
FROM BOARD BD, USERS U
WHERE 
BD.BD_WRITER = U.USER_ID
AND
BD_CATEGORY = 1 
AND 
BD_STATE = 1;

무피/문의 게시글 조회

SELECT 
  BD_NO
, BD_NAME
, BD_CONTENT
, BD_REGDATE
, BD_UPDATE
, U.NICKNAME
FROM BOARD BD, USERS U
WHERE 
BD.BD_WRITER = U.USER_ID
AND
BD_CATEGORY = 1      // 카테고리1번  무피게시글  2번 문의게시글
AND
BD.BD_NO = 10003    // 게시글번호
AND 
BD_STATE = 1;

무피 게시글 작성
INSERT INTO 
BOARD 
(
BD_NO
, BD_CATEGORY
, BD_WRITER
, BD_NAME
, BD_CONTENT
, BD_REGDATE
, BD_STATE
) 
VALUES 
(
'10015'
, '1'
, 'tkdgus403@naver.com'
, '공지사항!'
, '반갑습니다 무피입니다'
, TO_DATE('2021-07-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
, '1'
)

무피 게시글 삭제

UPDATE BOARD 
SET 
BD_STATE = '2'  // 스테이트 1번이 정상 2번이 삭제. ㅠㅜ 
WHERE 
BD_NO =  // 게시글번호

무피 게시글 수정

UPDATE 
BOARD 
SET 
  BD_NAME = '제목수정'
, BD_CONTENT = '내용수정'
, BD_UPDATE = TO_DATE('2021-07-08 18:33:12', 'YYYY-MM-DD HH24:MI:SS')
, BD_STATE = '2' 
WHERE 
BD_NO =  // 게시글번호

문의게시판 리스트

SELECT 
    BD.BD_NO
  , U.NICKNAME
  , BD.BD_NAME
  , BD.BD_REGDATE
  , BD.BD_UPDATE
  , BD.BD_PASSWORD
  , COUNT(R.REPLY_CONTENT) REPLYCOUNT
  FROM BOARD BD, USERS U, REPLY R
WHERE 
BD.BD_WRITER = U.USER_ID
AND
BD.BD_NO = R.BD_NO
AND
bd.bd_category = 2
GROUP BY BD.BD_NO, U.NICKNAME, BD.BD_NAME, BD.BD_REGDATE, 
BD.BD_UPDATE, BD.BD_PASSWORD

문의게시글 조회(내용 + 답글)
SELECT 
  B.BD_NO
, B.BD_NAME
, B.BD_CONTENT
, B.BD_REGDATE
, B.BD_UPDATE
, B.BD_WRITER
, R.REPLY_CONTENT
, R.REPLY_REGDATE
, R.REPLY_WRITER_ID
, r.reply_file
FROM
BOARD B
FULL OUTER JOIN REPLY R 
ON
B.BD_NO = R.BD_NO
WHERE 
R.BD_NO = 10004 



댓글 내용 겟.
SELECT 
  r.bd_no
, REPLY_CONTENT
, REPLY_REGDATE
, u1.nickname
FROM
REPLY R, USERS U1
WHERE 
R.BD_NO = 10004
AND
r.reply_writer_id = U1.USER_ID
GROUP BY
r.reply_content, R.REPLY_REGDATE, U1.NICKNAME,
U1.USER_ID, R.BD_NO

테스트중! {
SELECT 
    BD.BD_NO
  , U.NICKNAME
  , u.profile_image
  , BD.BD_NAME
  , BD.BD_REGDATE
  , BD.BD_UPDATE
  , BD.BD_PASSWORD
  , COUNT(R.REPLY_CONTENT) REPLYCOUNT
  FROM BOARD BD, USERS U, REPLY R
WHERE 
BD.BD_WRITER = U.USER_ID
AND
BD.BD_NO = R.BD_NO
AND
bd.bd_category = 2
GROUP BY BD.BD_NO, U.NICKNAME, BD.BD_NAME, u.profile_image, BD.BD_REGDATE, 
BD.BD_UPDATE, BD.BD_PASSWORD

SELECT 
    BD.BD_NO
  , bd.bd_writer
  , BD.BD_NAME
  , BD.BD_REGDATE
  , BD.BD_UPDATE
  , BD.BD_PASSWORD
  , COUNT(R.REPLY_CONTENT) REPLYCOUNT
  FROM BOARD BD, REPLY R
WHERE 
BD.BD_NO = R.BD_NO
AND
bd.bd_category = 2
GROUP BY BD.BD_NO, BD.BD_NAME, bd.bd_writer, BD.BD_REGDATE, BD.BD_UPDATE, 
BD.BD_PASSWORD
}